services:
  codrr_pg:
    image: postgres:15.1
    container_name: codrr_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codrrdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql